name: 'String Manipulation Action'
description: 'Break down strings based on uppercase or dash and output sections'
inputs:
  inputString:
    description: 'String to process (default: current repository name)'
    required: false
    default: ${{ github.repository }}
outputs:
  plugin_org:
    description: "repo org"
  plugin_id:
    description: "plugin id"
runs:
  using: 'node16'
  main: 'index.js'
