name: Test Current Gaction

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  job_test_current_gaction:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: "Test current gaction"
        id: step_test_current_gaction
        uses: SweetRainGarden/SrgGactionNameTransferJs@develop
        with:
          inputString: " ${{ github.event.repository.name }}"
      - name: "Echo step output"
        id: step_echo_output
        run: |
          echo "plugin_org=${{ steps.step_test_current_gaction.outputs.plugin_org }}"
          echo "plugin_id=${{ steps.step_test_current_gaction.outputs.plugin_id }}"
          echo "name_prefix=${{ steps.step_test_current_gaction.outputs.name_prefix }}"
          echo "name_suffix=${{ steps.step_test_current_gaction.outputs.name_suffix }}"
          echo "name_middle_section=${{ steps.step_test_current_gaction.outputs.name_middle_section }}"
          echo "full_com_plugin_format=${{ steps.step_test_current_gaction.outputs.full_com_plugin_format }}"
